/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CiteRemoverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CITE_REGEX = /\[cite_start\]|\[cite:[^\]]*\]/g;
var CiteRemoverPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "remove-cite-current-file",
      name: "Remove cite tags from current file",
      editorCallback: (editor, view) => {
        const currentText = editor.getValue();
        if (!currentText.match(CITE_REGEX)) {
          new import_obsidian.Notice("No cite tags found in this file.");
          return;
        }
        const newText = currentText.replace(CITE_REGEX, "");
        editor.setValue(newText);
        new import_obsidian.Notice("Cite tags removed from current file.");
      }
    });
    this.addCommand({
      id: "remove-cite-all-files",
      name: "Remove cite tags from ENTIRE Vault (with backup)",
      callback: async () => {
        if (!confirm("Are you sure you want to remove cite tags from ALL files in the vault? .bak files will be created.")) {
          return;
        }
        const files = this.app.vault.getMarkdownFiles();
        let processedCount = 0;
        let errorCount = 0;
        new import_obsidian.Notice(`Processing ${files.length} files...`);
        for (const file of files) {
          try {
            await this.processFile(file);
            processedCount++;
          } catch (e) {
            console.error(`Failed to process ${file.path}`, e);
            errorCount++;
          }
        }
        new import_obsidian.Notice(`Complete! Processed: ${processedCount}, Errors: ${errorCount}`);
      }
    });
  }
  // 파일 처리 로직 (읽기 -> 치환 -> 백업 -> 쓰기)
  async processFile(file) {
    const content = await this.app.vault.read(file);
    if (!content.match(CITE_REGEX)) {
      return;
    }
    const newContent = content.replace(CITE_REGEX, "");
    try {
      await this.app.vault.create(file.path + ".bak", content);
    } catch (error) {
      console.log(`Backup skipped for ${file.path}: file likely exists.`);
    }
    await this.app.vault.modify(file, newContent);
  }
};
